name: Release
concurrency: release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  release:
    uses: onlyspans/gh-workflows/.github/workflows/release.yml@main
    permissions:
      contents: write
    with:
      image_name: frontend
      helm_release: frontend-staging
      kube_namespace: frontend
      extra_build_args: |
        VITE_API_URL=${{ vars.VITE_API_URL }}
    secrets: inherit
