name: Release
concurrency: release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  release:
    uses: onlyspans/gh-workflows/.github/workflows/release.yml@main
    with:
      image_name: frontend
      helm_release: frontend-staging
      kube_namespace: frontend
    secrets: inherit
